# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUINext_refer.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(750, 500)
        self.back = QtWidgets.QFrame(Dialog)
        self.back.setGeometry(QtCore.QRect(9, 9, 741, 491))
        self.back.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.back.setFrameShadow(QtWidgets.QFrame.Raised)
        self.back.setObjectName("back")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.back)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.canvas = QtWidgets.QWidget(self.back)
        self.canvas.setMinimumSize(QtCore.QSize(0, 0))
        self.canvas.setObjectName("canvas")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.canvas)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graph_widget = QtWidgets.QWidget(self.canvas)
        self.graph_widget.setObjectName("graph_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.graph_widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pie_widget = QtWidgets.QWidget(self.graph_widget)
        self.pie_widget.setMinimumSize(QtCore.QSize(300, 200))
        self.pie_widget.setObjectName("pie_widget")
        self.CurrentScore = QtWidgets.QLabel(self.pie_widget)
        self.CurrentScore.setGeometry(QtCore.QRect(230, 10, 81, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CurrentScore.sizePolicy().hasHeightForWidth())
        self.CurrentScore.setSizePolicy(sizePolicy)
        self.CurrentScore.setMinimumSize(QtCore.QSize(20, 20))
        self.CurrentScore.setMaximumSize(QtCore.QSize(300, 120))
        font = QtGui.QFont()
        font.setFamily("Brush Script Std")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.CurrentScore.setFont(font)
        self.CurrentScore.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentScore.setObjectName("CurrentScore")
        self.CurrentScore_3 = QtWidgets.QLabel(self.pie_widget)
        self.CurrentScore_3.setGeometry(QtCore.QRect(20, 0, 201, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CurrentScore_3.sizePolicy().hasHeightForWidth())
        self.CurrentScore_3.setSizePolicy(sizePolicy)
        self.CurrentScore_3.setMinimumSize(QtCore.QSize(20, 20))
        self.CurrentScore_3.setMaximumSize(QtCore.QSize(300, 120))
        font = QtGui.QFont()
        font.setFamily("Brush Script Std")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.CurrentScore_3.setFont(font)
        self.CurrentScore_3.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentScore_3.setObjectName("CurrentScore_3")
        self.badge1 = QtWidgets.QLabel(self.pie_widget)
        self.badge1.setGeometry(QtCore.QRect(420, 40, 61, 51))
        self.badge1.setText("")
        self.badge1.setObjectName("badge1")
        self.badge2 = QtWidgets.QLabel(self.pie_widget)
        self.badge2.setGeometry(QtCore.QRect(520, 40, 61, 51))
        self.badge2.setText("")
        self.badge2.setObjectName("badge2")
        self.badge3 = QtWidgets.QLabel(self.pie_widget)
        self.badge3.setGeometry(QtCore.QRect(610, 40, 61, 51))
        self.badge3.setText("")
        self.badge3.setObjectName("badge3")
        self.trip_points_text = QtWidgets.QLabel(self.pie_widget)
        self.trip_points_text.setGeometry(QtCore.QRect(20, 60, 201, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trip_points_text.sizePolicy().hasHeightForWidth())
        self.trip_points_text.setSizePolicy(sizePolicy)
        self.trip_points_text.setMinimumSize(QtCore.QSize(20, 20))
        self.trip_points_text.setMaximumSize(QtCore.QSize(300, 120))
        font = QtGui.QFont()
        font.setFamily("Brush Script Std")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.trip_points_text.setFont(font)
        self.trip_points_text.setAlignment(QtCore.Qt.AlignCenter)
        self.trip_points_text.setObjectName("trip_points_text")
        self.trip_points_score = QtWidgets.QLabel(self.pie_widget)
        self.trip_points_score.setGeometry(QtCore.QRect(230, 70, 81, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trip_points_score.sizePolicy().hasHeightForWidth())
        self.trip_points_score.setSizePolicy(sizePolicy)
        self.trip_points_score.setMinimumSize(QtCore.QSize(20, 20))
        self.trip_points_score.setMaximumSize(QtCore.QSize(300, 120))
        font = QtGui.QFont()
        font.setFamily("Brush Script Std")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.trip_points_score.setFont(font)
        self.trip_points_score.setAlignment(QtCore.Qt.AlignCenter)
        self.trip_points_score.setObjectName("trip_points_score")
        self.total_points_text = QtWidgets.QLabel(self.pie_widget)
        self.total_points_text.setGeometry(QtCore.QRect(20, 130, 201, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.total_points_text.sizePolicy().hasHeightForWidth())
        self.total_points_text.setSizePolicy(sizePolicy)
        self.total_points_text.setMinimumSize(QtCore.QSize(20, 20))
        self.total_points_text.setMaximumSize(QtCore.QSize(300, 120))
        font = QtGui.QFont()
        font.setFamily("Brush Script Std")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.total_points_text.setFont(font)
        self.total_points_text.setAlignment(QtCore.Qt.AlignCenter)
        self.total_points_text.setObjectName("total_points_text")
        self.total_points_score = QtWidgets.QLabel(self.pie_widget)
        self.total_points_score.setGeometry(QtCore.QRect(230, 140, 81, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.total_points_score.sizePolicy().hasHeightForWidth())
        self.total_points_score.setSizePolicy(sizePolicy)
        self.total_points_score.setMinimumSize(QtCore.QSize(20, 20))
        self.total_points_score.setMaximumSize(QtCore.QSize(300, 120))
        font = QtGui.QFont()
        font.setFamily("Brush Script Std")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.total_points_score.setFont(font)
        self.total_points_score.setAlignment(QtCore.Qt.AlignCenter)
        self.total_points_score.setObjectName("total_points_score")
        self.horizontalLayout_2.addWidget(self.pie_widget)
        self.verticalLayout.addWidget(self.graph_widget)
        self.plot_widget = PlotWidget(self.canvas)
        self.plot_widget.setObjectName("plot_widget")
        self.verticalLayout.addWidget(self.plot_widget)
        self.verticalLayout_2.addWidget(self.canvas)
        self.down = QtWidgets.QWidget(self.back)
        self.down.setMinimumSize(QtCore.QSize(0, 50))
        self.down.setMaximumSize(QtCore.QSize(16777215, 50))
        self.down.setObjectName("down")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.down)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.backBtn = QtWidgets.QPushButton(self.down)
        self.backBtn.setMaximumSize(QtCore.QSize(60, 16777215))
        self.backBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.backBtn.setAutoFillBackground(False)
        self.backBtn.setDefault(False)
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout.addWidget(self.backBtn)
        self.verticalLayout_2.addWidget(self.down)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.CurrentScore.setText(_translate("Dialog", "86"))
        self.CurrentScore_3.setText(_translate("Dialog", "Average Score:"))
        self.trip_points_text.setText(_translate("Dialog", "trip points"))
        self.trip_points_score.setText(_translate("Dialog", "86"))
        self.total_points_text.setText(_translate("Dialog", "total points"))
        self.total_points_score.setText(_translate("Dialog", "86"))
        self.backBtn.setText(_translate("Dialog", "back"))
from pyqtgraph import PlotWidget
