# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUINext_refer.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(750, 500)
        self.back = QtWidgets.QFrame(Dialog)
        self.back.setGeometry(QtCore.QRect(9, 9, 741, 491))
        self.back.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.back.setFrameShadow(QtWidgets.QFrame.Raised)
        self.back.setObjectName("back")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.back)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.canvas = QtWidgets.QWidget(self.back)
        self.canvas.setMinimumSize(QtCore.QSize(0, 0))
        self.canvas.setObjectName("canvas")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.canvas)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graph_widget = QtWidgets.QWidget(self.canvas)
        self.graph_widget.setObjectName("graph_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.graph_widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pie_widget = QtWidgets.QWidget(self.graph_widget)
        self.pie_widget.setMinimumSize(QtCore.QSize(300, 200))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.pie_widget.setFont(font)
        self.pie_widget.setObjectName("pie_widget")
        self.summary_text = QtWidgets.QLabel(self.pie_widget)
        self.summary_text.setGeometry(QtCore.QRect(230, 0, 231, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.summary_text.sizePolicy().hasHeightForWidth())
        self.summary_text.setSizePolicy(sizePolicy)
        self.summary_text.setMinimumSize(QtCore.QSize(20, 20))
        self.summary_text.setMaximumSize(QtCore.QSize(300, 120))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.summary_text.setFont(font)
        self.summary_text.setAlignment(QtCore.Qt.AlignCenter)
        self.summary_text.setObjectName("summary_text")
        self.Total_coins_text = QtWidgets.QLabel(self.pie_widget)
        self.Total_coins_text.setGeometry(QtCore.QRect(530, 70, 131, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Total_coins_text.sizePolicy().hasHeightForWidth())
        self.Total_coins_text.setSizePolicy(sizePolicy)
        self.Total_coins_text.setMinimumSize(QtCore.QSize(20, 20))
        self.Total_coins_text.setMaximumSize(QtCore.QSize(300, 120))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Total_coins_text.setFont(font)
        self.Total_coins_text.setAlignment(QtCore.Qt.AlignCenter)
        self.Total_coins_text.setObjectName("Total_coins_text")
        self.Coins_earned_text = QtWidgets.QLabel(self.pie_widget)
        self.Coins_earned_text.setGeometry(QtCore.QRect(360, 70, 131, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Coins_earned_text.sizePolicy().hasHeightForWidth())
        self.Coins_earned_text.setSizePolicy(sizePolicy)
        self.Coins_earned_text.setMinimumSize(QtCore.QSize(20, 20))
        self.Coins_earned_text.setMaximumSize(QtCore.QSize(300, 120))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Coins_earned_text.setFont(font)
        self.Coins_earned_text.setAlignment(QtCore.Qt.AlignCenter)
        self.Coins_earned_text.setObjectName("Coins_earned_text")
        self.coins_earned_score = QtWidgets.QLabel(self.pie_widget)
        self.coins_earned_score.setGeometry(QtCore.QRect(380, 120, 101, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coins_earned_score.sizePolicy().hasHeightForWidth())
        self.coins_earned_score.setSizePolicy(sizePolicy)
        self.coins_earned_score.setMinimumSize(QtCore.QSize(20, 20))
        self.coins_earned_score.setMaximumSize(QtCore.QSize(300, 120))
        font = QtGui.QFont()
        font.setFamily("Brush Script Std")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.coins_earned_score.setFont(font)
        self.coins_earned_score.setAlignment(QtCore.Qt.AlignCenter)
        self.coins_earned_score.setObjectName("coins_earned_score")
        self.tota_coins_score = QtWidgets.QLabel(self.pie_widget)
        self.tota_coins_score.setGeometry(QtCore.QRect(550, 130, 81, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tota_coins_score.sizePolicy().hasHeightForWidth())
        self.tota_coins_score.setSizePolicy(sizePolicy)
        self.tota_coins_score.setMinimumSize(QtCore.QSize(20, 20))
        self.tota_coins_score.setMaximumSize(QtCore.QSize(300, 120))
        font = QtGui.QFont()
        font.setFamily("Brush Script Std")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tota_coins_score.setFont(font)
        self.tota_coins_score.setAlignment(QtCore.Qt.AlignCenter)
        self.tota_coins_score.setObjectName("tota_coins_score")
        self.trip_score_text = QtWidgets.QLabel(self.pie_widget)
        self.trip_score_text.setGeometry(QtCore.QRect(190, 70, 131, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trip_score_text.sizePolicy().hasHeightForWidth())
        self.trip_score_text.setSizePolicy(sizePolicy)
        self.trip_score_text.setMinimumSize(QtCore.QSize(20, 20))
        self.trip_score_text.setMaximumSize(QtCore.QSize(300, 120))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.trip_score_text.setFont(font)
        self.trip_score_text.setAlignment(QtCore.Qt.AlignCenter)
        self.trip_score_text.setObjectName("trip_score_text")
        self.trip_score_score = QtWidgets.QLabel(self.pie_widget)
        self.trip_score_score.setGeometry(QtCore.QRect(210, 120, 101, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trip_score_score.sizePolicy().hasHeightForWidth())
        self.trip_score_score.setSizePolicy(sizePolicy)
        self.trip_score_score.setMinimumSize(QtCore.QSize(20, 20))
        self.trip_score_score.setMaximumSize(QtCore.QSize(300, 120))
        font = QtGui.QFont()
        font.setFamily("Brush Script Std")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.trip_score_score.setFont(font)
        self.trip_score_score.setAlignment(QtCore.Qt.AlignCenter)
        self.trip_score_score.setObjectName("trip_score_score")
        self.Personal_score_text = QtWidgets.QLabel(self.pie_widget)
        self.Personal_score_text.setGeometry(QtCore.QRect(30, 70, 131, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Personal_score_text.sizePolicy().hasHeightForWidth())
        self.Personal_score_text.setSizePolicy(sizePolicy)
        self.Personal_score_text.setMinimumSize(QtCore.QSize(20, 20))
        self.Personal_score_text.setMaximumSize(QtCore.QSize(300, 120))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Personal_score_text.setFont(font)
        self.Personal_score_text.setAlignment(QtCore.Qt.AlignCenter)
        self.Personal_score_text.setObjectName("Personal_score_text")
        self.personal_score_score = QtWidgets.QLabel(self.pie_widget)
        self.personal_score_score.setGeometry(QtCore.QRect(50, 120, 81, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.personal_score_score.sizePolicy().hasHeightForWidth())
        self.personal_score_score.setSizePolicy(sizePolicy)
        self.personal_score_score.setMinimumSize(QtCore.QSize(20, 20))
        self.personal_score_score.setMaximumSize(QtCore.QSize(300, 120))
        font = QtGui.QFont()
        font.setFamily("Brush Script Std")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.personal_score_score.setFont(font)
        self.personal_score_score.setAlignment(QtCore.Qt.AlignCenter)
        self.personal_score_score.setObjectName("personal_score_score")
        self.Badge_img = QtWidgets.QLabel(self.pie_widget)
        self.Badge_img.setGeometry(QtCore.QRect(40, 20, 91, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Badge_img.sizePolicy().hasHeightForWidth())
        self.Badge_img.setSizePolicy(sizePolicy)
        self.Badge_img.setMinimumSize(QtCore.QSize(20, 20))
        self.Badge_img.setMaximumSize(QtCore.QSize(300, 120))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Badge_img.setFont(font)
        self.Badge_img.setText("")
        self.Badge_img.setAlignment(QtCore.Qt.AlignCenter)
        self.Badge_img.setObjectName("Badge_img")
        self.Coin_img = QtWidgets.QLabel(self.pie_widget)
        self.Coin_img.setGeometry(QtCore.QRect(550, 20, 91, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Coin_img.sizePolicy().hasHeightForWidth())
        self.Coin_img.setSizePolicy(sizePolicy)
        self.Coin_img.setMinimumSize(QtCore.QSize(20, 20))
        self.Coin_img.setMaximumSize(QtCore.QSize(300, 120))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Coin_img.setFont(font)
        self.Coin_img.setText("")
        self.Coin_img.setAlignment(QtCore.Qt.AlignCenter)
        self.Coin_img.setObjectName("Coin_img")
        self.horizontalLayout_2.addWidget(self.pie_widget)
        self.verticalLayout.addWidget(self.graph_widget)
        self.plot_widget = PlotWidget(self.canvas)
        self.plot_widget.setObjectName("plot_widget")
        self.verticalLayout.addWidget(self.plot_widget)
        self.verticalLayout_2.addWidget(self.canvas)
        self.down = QtWidgets.QWidget(self.back)
        self.down.setMinimumSize(QtCore.QSize(0, 50))
        self.down.setMaximumSize(QtCore.QSize(16777215, 50))
        self.down.setObjectName("down")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.down)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.backBtn = QtWidgets.QPushButton(self.down)
        self.backBtn.setMaximumSize(QtCore.QSize(60, 16777215))
        self.backBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.backBtn.setAutoFillBackground(False)
        self.backBtn.setDefault(False)
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout.addWidget(self.backBtn)
        self.verticalLayout_2.addWidget(self.down)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.summary_text.setText(_translate("Dialog", "Summary"))
        self.Total_coins_text.setText(_translate("Dialog", "Total Coins"))
        self.Coins_earned_text.setText(_translate("Dialog", "Coins Earned"))
        self.coins_earned_score.setText(_translate("Dialog", "9"))
        self.tota_coins_score.setText(_translate("Dialog", "86"))
        self.trip_score_text.setText(_translate("Dialog", "Trip Score"))
        self.trip_score_score.setText(_translate("Dialog", "86"))
        self.Personal_score_text.setText(_translate("Dialog", "Personal Score"))
        self.personal_score_score.setText(_translate("Dialog", "91"))
        self.backBtn.setText(_translate("Dialog", "back"))
from pyqtgraph import PlotWidget
